name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Download kode dari repositori
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Langkah 2: Setup Docker Buildx (fitur build Docker modern & cepat)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Langkah 3: Login ke Docker Hub menggunakan GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Langkah 4: Build image dan Push ke Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Mengatur tag otomatis: versi 'latest' dan versi berdasarkan SHA commit GitHub
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/github-action-app:latest
            ${{ secrets.DOCKER_USERNAME }}/github-action-app:${{ github.sha }}
